module.exports = analyze;
function analyze(text, cb) {
  retext.process(text, cb);
}

const retext = require('retext')()
  .use(require('retext-cliches'))
  .use(require('retext-contractions'))
  .use(require('retext-diacritics'))
  .use(require('retext-dutch'))
  .use(require('retext-emoji'))
  .use(require('retext-english'))
  .use(require('retext-equality'))
  .use(require('retext-indefinite-article'))
  .use(require('retext-keywords'))
  .use(require('retext-latin'))
  .use(require('retext-overuse'))
  .use(require('retext-passive'))
  .use(require('retext-profanities'))
  .use(require('retext-quotes'))
  .use(require('retext-readability'))
  .use(require('retext-redundant-acronyms'))
  .use(require('retext-repeated-words'))
  .use(require('retext-sentence-spacing'))
  .use(require('retext-sentiment'))
  .use(require('retext-simplify'))
  .use(require('retext-smartypants'))
  .use(require('retext-stringify'))
  .use(require('retext-syntax-mentions'))
  .use(require('retext-usage'))
  // .use(require('retext-spell'), require('dictionary-en-us'))
